// Country data with DDI (Dial Direct Inward) codes
export interface CountryData {
  name: string;
  code: string; // ISO 3166-1 alpha-2
  ddi: string; // International dialing code
  flag: string; // Emoji flag
}

export const COUNTRIES_WITH_DDI: CountryData[] = [
  { name: "Afghanistan", code: "AF", ddi: "+93", flag: "🇦🇫" },
  { name: "Albania", code: "AL", ddi: "+355", flag: "🇦🇱" },
  { name: "Algeria", code: "DZ", ddi: "+213", flag: "🇩🇿" },
  { name: "Andorra", code: "AD", ddi: "+376", flag: "🇦🇩" },
  { name: "Angola", code: "AO", ddi: "+244", flag: "🇦🇴" },
  { name: "Argentina", code: "AR", ddi: "+54", flag: "🇦🇷" },
  { name: "Armenia", code: "AM", ddi: "+374", flag: "🇦🇲" },
  { name: "Australia", code: "AU", ddi: "+61", flag: "🇦🇺" },
  { name: "Austria", code: "AT", ddi: "+43", flag: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", ddi: "+994", flag: "🇦🇿" },
  { name: "Bahamas", code: "BS", ddi: "+1-242", flag: "🇧🇸" },
  { name: "Bahrain", code: "BH", ddi: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", code: "BD", ddi: "+880", flag: "🇧🇩" },
  { name: "Barbados", code: "BB", ddi: "+1-246", flag: "🇧🇧" },
  { name: "Belarus", code: "BY", ddi: "+375", flag: "🇧🇾" },
  { name: "Belgium", code: "BE", ddi: "+32", flag: "🇧🇪" },
  { name: "Belize", code: "BZ", ddi: "+501", flag: "🇧🇿" },
  { name: "Benin", code: "BJ", ddi: "+229", flag: "🇧🇯" },
  { name: "Bhutan", code: "BT", ddi: "+975", flag: "🇧🇹" },
  { name: "Bolivia", code: "BO", ddi: "+591", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", code: "BA", ddi: "+387", flag: "🇧🇦" },
  { name: "Botswana", code: "BW", ddi: "+267", flag: "🇧🇼" },
  { name: "Brazil", code: "BR", ddi: "+55", flag: "🇧🇷" },
  { name: "Brunei", code: "BN", ddi: "+673", flag: "🇧🇳" },
  { name: "Bulgaria", code: "BG", ddi: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", ddi: "+226", flag: "🇧🇫" },
  { name: "Burundi", code: "BI", ddi: "+257", flag: "🇧🇮" },
  { name: "Cambodia", code: "KH", ddi: "+855", flag: "🇰🇭" },
  { name: "Cameroon", code: "CM", ddi: "+237", flag: "🇨🇲" },
  { name: "Canada", code: "CA", ddi: "+1", flag: "🇨🇦" },
  { name: "Cape Verde", code: "CV", ddi: "+238", flag: "🇨🇻" },
  { name: "Central African Republic", code: "CF", ddi: "+236", flag: "🇨🇫" },
  { name: "Chad", code: "TD", ddi: "+235", flag: "🇹🇩" },
  { name: "Chile", code: "CL", ddi: "+56", flag: "🇨🇱" },
  { name: "China", code: "CN", ddi: "+86", flag: "🇨🇳" },
  { name: "Colombia", code: "CO", ddi: "+57", flag: "🇨🇴" },
  { name: "Comoros", code: "KM", ddi: "+269", flag: "🇰🇲" },
  { name: "Congo", code: "CG", ddi: "+242", flag: "🇨🇬" },
  { name: "Costa Rica", code: "CR", ddi: "+506", flag: "🇨🇷" },
  { name: "Croatia", code: "HR", ddi: "+385", flag: "🇭🇷" },
  { name: "Cuba", code: "CU", ddi: "+53", flag: "🇨🇺" },
  { name: "Cyprus", code: "CY", ddi: "+357", flag: "🇨🇾" },
  { name: "Czech Republic", code: "CZ", ddi: "+420", flag: "🇨🇿" },
  { name: "Denmark", code: "DK", ddi: "+45", flag: "🇩🇰" },
  { name: "Djibouti", code: "DJ", ddi: "+253", flag: "🇩🇯" },
  { name: "Dominica", code: "DM", ddi: "+1-767", flag: "🇩🇲" },
  { name: "Dominican Republic", code: "DO", ddi: "+1-809", flag: "🇩🇴" },
  { name: "Ecuador", code: "EC", ddi: "+593", flag: "🇪🇨" },
  { name: "Egypt", code: "EG", ddi: "+20", flag: "🇪🇬" },
  { name: "El Salvador", code: "SV", ddi: "+503", flag: "🇸🇻" },
  { name: "Equatorial Guinea", code: "GQ", ddi: "+240", flag: "🇬🇶" },
  { name: "Eritrea", code: "ER", ddi: "+291", flag: "🇪🇷" },
  { name: "Estonia", code: "EE", ddi: "+372", flag: "🇪🇪" },
  { name: "Ethiopia", code: "ET", ddi: "+251", flag: "🇪🇹" },
  { name: "Fiji", code: "FJ", ddi: "+679", flag: "🇫🇯" },
  { name: "Finland", code: "FI", ddi: "+358", flag: "🇫🇮" },
  { name: "France", code: "FR", ddi: "+33", flag: "🇫🇷" },
  { name: "Gabon", code: "GA", ddi: "+241", flag: "🇬🇦" },
  { name: "Gambia", code: "GM", ddi: "+220", flag: "🇬🇲" },
  { name: "Georgia", code: "GE", ddi: "+995", flag: "🇬🇪" },
  { name: "Germany", code: "DE", ddi: "+49", flag: "🇩🇪" },
  { name: "Ghana", code: "GH", ddi: "+233", flag: "🇬🇭" },
  { name: "Greece", code: "GR", ddi: "+30", flag: "🇬🇷" },
  { name: "Grenada", code: "GD", ddi: "+1-473", flag: "🇬🇩" },
  { name: "Guatemala", code: "GT", ddi: "+502", flag: "🇬🇹" },
  { name: "Guinea", code: "GN", ddi: "+224", flag: "🇬🇳" },
  { name: "Guinea-Bissau", code: "GW", ddi: "+245", flag: "🇬🇼" },
  { name: "Guyana", code: "GY", ddi: "+592", flag: "🇬🇾" },
  { name: "Haiti", code: "HT", ddi: "+509", flag: "🇭🇹" },
  { name: "Honduras", code: "HN", ddi: "+504", flag: "🇭🇳" },
  { name: "Hungary", code: "HU", ddi: "+36", flag: "🇭🇺" },
  { name: "Iceland", code: "IS", ddi: "+354", flag: "🇮🇸" },
  { name: "India", code: "IN", ddi: "+91", flag: "🇮🇳" },
  { name: "Indonesia", code: "ID", ddi: "+62", flag: "🇮🇩" },
  { name: "Iran", code: "IR", ddi: "+98", flag: "🇮🇷" },
  { name: "Iraq", code: "IQ", ddi: "+964", flag: "🇮🇶" },
  { name: "Ireland", code: "IE", ddi: "+353", flag: "🇮🇪" },
  { name: "Israel", code: "IL", ddi: "+972", flag: "🇮🇱" },
  { name: "Italy", code: "IT", ddi: "+39", flag: "🇮🇹" },
  { name: "Jamaica", code: "JM", ddi: "+1-876", flag: "🇯🇲" },
  { name: "Japan", code: "JP", ddi: "+81", flag: "🇯🇵" },
  { name: "Jordan", code: "JO", ddi: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", ddi: "+7", flag: "🇰🇿" },
  { name: "Kenya", code: "KE", ddi: "+254", flag: "🇰🇪" },
  { name: "Kiribati", code: "KI", ddi: "+686", flag: "🇰🇮" },
  { name: "Kuwait", code: "KW", ddi: "+965", flag: "🇰🇼" },
  { name: "Kyrgyzstan", code: "KG", ddi: "+996", flag: "🇰🇬" },
  { name: "Laos", code: "LA", ddi: "+856", flag: "🇱🇦" },
  { name: "Latvia", code: "LV", ddi: "+371", flag: "🇱🇻" },
  { name: "Lebanon", code: "LB", ddi: "+961", flag: "🇱🇧" },
  { name: "Lesotho", code: "LS", ddi: "+266", flag: "🇱🇸" },
  { name: "Liberia", code: "LR", ddi: "+231", flag: "🇱🇷" },
  { name: "Libya", code: "LY", ddi: "+218", flag: "🇱🇾" },
  { name: "Liechtenstein", code: "LI", ddi: "+423", flag: "🇱🇮" },
  { name: "Lithuania", code: "LT", ddi: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LU", ddi: "+352", flag: "🇱🇺" },
  { name: "Madagascar", code: "MG", ddi: "+261", flag: "🇲🇬" },
  { name: "Malawi", code: "MW", ddi: "+265", flag: "🇲🇼" },
  { name: "Malaysia", code: "MY", ddi: "+60", flag: "🇲🇾" },
  { name: "Maldives", code: "MV", ddi: "+960", flag: "🇲🇻" },
  { name: "Mali", code: "ML", ddi: "+223", flag: "🇲🇱" },
  { name: "Malta", code: "MT", ddi: "+356", flag: "🇲🇹" },
  { name: "Marshall Islands", code: "MH", ddi: "+692", flag: "🇲🇭" },
  { name: "Mauritania", code: "MR", ddi: "+222", flag: "🇲🇷" },
  { name: "Mauritius", code: "MU", ddi: "+230", flag: "🇲🇺" },
  { name: "Mexico", code: "MX", ddi: "+52", flag: "🇲🇽" },
  { name: "Micronesia", code: "FM", ddi: "+691", flag: "🇫🇲" },
  { name: "Moldova", code: "MD", ddi: "+373", flag: "🇲🇩" },
  { name: "Monaco", code: "MC", ddi: "+377", flag: "🇲🇨" },
  { name: "Mongolia", code: "MN", ddi: "+976", flag: "🇲🇳" },
  { name: "Montenegro", code: "ME", ddi: "+382", flag: "🇲🇪" },
  { name: "Morocco", code: "MA", ddi: "+212", flag: "🇲🇦" },
  { name: "Mozambique", code: "MZ", ddi: "+258", flag: "🇲🇿" },
  { name: "Myanmar", code: "MM", ddi: "+95", flag: "🇲🇲" },
  { name: "Namibia", code: "NA", ddi: "+264", flag: "🇳🇦" },
  { name: "Nauru", code: "NR", ddi: "+674", flag: "🇳🇷" },
  { name: "Nepal", code: "NP", ddi: "+977", flag: "🇳🇵" },
  { name: "Netherlands", code: "NL", ddi: "+31", flag: "🇳🇱" },
  { name: "New Zealand", code: "NZ", ddi: "+64", flag: "🇳🇿" },
  { name: "Nicaragua", code: "NI", ddi: "+505", flag: "🇳🇮" },
  { name: "Niger", code: "NE", ddi: "+227", flag: "🇳🇪" },
  { name: "Nigeria", code: "NG", ddi: "+234", flag: "🇳🇬" },
  { name: "North Korea", code: "KP", ddi: "+850", flag: "🇰🇵" },
  { name: "North Macedonia", code: "MK", ddi: "+389", flag: "🇲🇰" },
  { name: "Norway", code: "NO", ddi: "+47", flag: "🇳🇴" },
  { name: "Oman", code: "OM", ddi: "+968", flag: "🇴🇲" },
  { name: "Pakistan", code: "PK", ddi: "+92", flag: "🇵🇰" },
  { name: "Palau", code: "PW", ddi: "+680", flag: "🇵🇼" },
  { name: "Palestine", code: "PS", ddi: "+970", flag: "🇵🇸" },
  { name: "Panama", code: "PA", ddi: "+507", flag: "🇵🇦" },
  { name: "Papua New Guinea", code: "PG", ddi: "+675", flag: "🇵🇬" },
  { name: "Paraguay", code: "PY", ddi: "+595", flag: "🇵🇾" },
  { name: "Peru", code: "PE", ddi: "+51", flag: "🇵🇪" },
  { name: "Philippines", code: "PH", ddi: "+63", flag: "🇵🇭" },
  { name: "Poland", code: "PL", ddi: "+48", flag: "🇵🇱" },
  { name: "Portugal", code: "PT", ddi: "+351", flag: "🇵🇹" },
  { name: "Qatar", code: "QA", ddi: "+974", flag: "🇶🇦" },
  { name: "Romania", code: "RO", ddi: "+40", flag: "🇷🇴" },
  { name: "Russia", code: "RU", ddi: "+7", flag: "🇷🇺" },
  { name: "Rwanda", code: "RW", ddi: "+250", flag: "🇷🇼" },
  { name: "Saint Kitts and Nevis", code: "KN", ddi: "+1-869", flag: "🇰🇳" },
  { name: "Saint Lucia", code: "LC", ddi: "+1-758", flag: "🇱🇨" },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    ddi: "+1-784",
    flag: "🇻🇨",
  },
  { name: "Samoa", code: "WS", ddi: "+685", flag: "🇼🇸" },
  { name: "San Marino", code: "SM", ddi: "+378", flag: "🇸🇲" },
  { name: "Sao Tome and Principe", code: "ST", ddi: "+239", flag: "🇸🇹" },
  { name: "Saudi Arabia", code: "SA", ddi: "+966", flag: "🇸🇦" },
  { name: "Senegal", code: "SN", ddi: "+221", flag: "🇸🇳" },
  { name: "Serbia", code: "RS", ddi: "+381", flag: "🇷🇸" },
  { name: "Seychelles", code: "SC", ddi: "+248", flag: "🇸🇨" },
  { name: "Sierra Leone", code: "SL", ddi: "+232", flag: "🇸🇱" },
  { name: "Singapore", code: "SG", ddi: "+65", flag: "🇸🇬" },
  { name: "Slovakia", code: "SK", ddi: "+421", flag: "🇸🇰" },
  { name: "Slovenia", code: "SI", ddi: "+386", flag: "🇸🇮" },
  { name: "Solomon Islands", code: "SB", ddi: "+677", flag: "🇸🇧" },
  { name: "Somalia", code: "SO", ddi: "+252", flag: "🇸🇴" },
  { name: "South Africa", code: "ZA", ddi: "+27", flag: "🇿🇦" },
  { name: "South Korea", code: "KR", ddi: "+82", flag: "🇰🇷" },
  { name: "South Sudan", code: "SS", ddi: "+211", flag: "🇸🇸" },
  { name: "Spain", code: "ES", ddi: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", code: "LK", ddi: "+94", flag: "🇱🇰" },
  { name: "Sudan", code: "SD", ddi: "+249", flag: "🇸🇩" },
  { name: "Suriname", code: "SR", ddi: "+597", flag: "🇸🇷" },
  { name: "Sweden", code: "SE", ddi: "+46", flag: "🇸🇪" },
  { name: "Switzerland", code: "CH", ddi: "+41", flag: "🇨🇭" },
  { name: "Syria", code: "SY", ddi: "+963", flag: "🇸🇾" },
  { name: "Taiwan", code: "TW", ddi: "+886", flag: "🇹🇼" },
  { name: "Tajikistan", code: "TJ", ddi: "+992", flag: "🇹🇯" },
  { name: "Tanzania", code: "TZ", ddi: "+255", flag: "🇹🇿" },
  { name: "Thailand", code: "TH", ddi: "+66", flag: "🇹🇭" },
  { name: "Timor-Leste", code: "TL", ddi: "+670", flag: "🇹🇱" },
  { name: "Togo", code: "TG", ddi: "+228", flag: "🇹🇬" },
  { name: "Tonga", code: "TO", ddi: "+676", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", code: "TT", ddi: "+1-868", flag: "🇹🇹" },
  { name: "Tunisia", code: "TN", ddi: "+216", flag: "🇹🇳" },
  { name: "Turkey", code: "TR", ddi: "+90", flag: "🇹🇷" },
  { name: "Turkmenistan", code: "TM", ddi: "+993", flag: "🇹🇲" },
  { name: "Tuvalu", code: "TV", ddi: "+688", flag: "🇹🇻" },
  { name: "Uganda", code: "UG", ddi: "+256", flag: "🇺🇬" },
  { name: "Ukraine", code: "UA", ddi: "+380", flag: "🇺🇦" },
  { name: "United Arab Emirates", code: "AE", ddi: "+971", flag: "🇦🇪" },
  { name: "United Kingdom", code: "GB", ddi: "+44", flag: "🇬🇧" },
  { name: "United States", code: "US", ddi: "+1", flag: "🇺🇸" },
  { name: "Uruguay", code: "UY", ddi: "+598", flag: "🇺🇾" },
  { name: "Uzbekistan", code: "UZ", ddi: "+998", flag: "🇺🇿" },
  { name: "Vanuatu", code: "VU", ddi: "+678", flag: "🇻🇺" },
  { name: "Vatican City", code: "VA", ddi: "+379", flag: "🇻🇦" },
  { name: "Venezuela", code: "VE", ddi: "+58", flag: "🇻🇪" },
  { name: "Vietnam", code: "VN", ddi: "+84", flag: "🇻🇳" },
  { name: "Yemen", code: "YE", ddi: "+967", flag: "🇾🇪" },
  { name: "Zambia", code: "ZM", ddi: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", ddi: "+263", flag: "🇿🇼" },
];

// Helper function to get DDI by country name
export function getDDIByCountry(countryName: string): string {
  const country = COUNTRIES_WITH_DDI.find(
    (c) => c.name.toLowerCase() === countryName.toLowerCase(),
  );
  return country?.ddi || "";
}

// Helper function to get country by DDI
export function getCountryByDDI(ddi: string): CountryData | undefined {
  return COUNTRIES_WITH_DDI.find((c) => c.ddi === ddi);
}
